// src/App.jsx
import { useEffect } from 'react';
import { _adtraceEvent, _adtraceGetAttribution, _adtraceGetUUID, _initAdtraceChannel } from './utils/adtrace'


export default function Home() {
    useEffect(() => {
        _initAdtraceChannel();
    }, [])
    
  
  return (
      <main>
          <h3>Adtrace Web SDK Demo (React.js) with power of vite</h3>
          
          <button
              
              onClick={() => _adtraceEvent({
                  eventToken: 'qpw44u',
                  revenue: 10,
                  currency: 'IRR',
                  callbackParams: [
                      {key: 'key', value: 'value'},
                      {key: 'foo', value: 'bar'}
                  ]
              })}
          >
              Event tracking
          </button>
          
          <button
            
              onClick={() => {
                  console.log(_adtraceGetAttribution())
              }}
          >
              GetAttribution (console)
          </button>

          <button
              
              onClick={() => {
                  console.log(_adtraceGetUUID())
              }}
          >
              GetWebUUID (console)
          </button>
      </main>
  )
}

// src/App.vue
<template>
  <div class="py-20 flex flex-col gap-8 items-center justify-center">
    <h1>Adtrace Web SDK Demo (Nuxt.js)</h1>
    <button @click="handleTriggerEvent">Event tracking</button>
    <button @click="handleGetAttribution">GetAttribution (console)</button>
    <button @click="handleGetUUID">GetWebUUID (console)</button>
  </div>
</template>

<script setup>
    import {_initAdtraceChannel, _adtraceEvent, _adtraceGetAttribution, _adtraceGetUUID } from './composables/useAdtrace'

    _initAdtraceChannel();

    const handleTriggerEvent = () => {
      _adtraceEvent({
          eventToken: 'qmrt2w',
          revenue: 10,
          currency: 'IRR',
          eventValueParams: [
              {key: 'key', value: 'value'},
              {key: 'foo', value: 'bar'}
          ],
      })
    }

    const handleGetAttribution = () => {
      const attribution = _adtraceGetAttribution();
      console.log(attribution);
    }

    const handleGetUUID = () => {
      const uuid = _adtraceGetUUID();
      console.log(uuid);
    }
</script>
